### ISSUE TITLE
Error inflating class com.samvel1024.databindingrv.BindingRecyclerView

### ISSUE THREAD

**Issue by Ragghwendra** [samvel1024/databinding-recyclerview#3]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mms/com.mms.architecture.view.TrainingList}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.samvel1024.databindingrv.BindingRecyclerView
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                           at android.os.Looper.loop(Looper.java:164)
                                                           at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                        Caused by: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.samvel1024.databindingrv.BindingRecyclerView
                                                        Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class com.samvel1024.databindingrv.BindingRecyclerView
                                                        Caused by: java.lang.reflect.InvocationTargetException

**Comment by samvel1024** [comment]
Please provide the xml file and any other relevant code.
